data: core/data/blind.yaml
hyp: core/hyp/scratch.yaml
epochs: 300
batch_size: 8
img_size:
- 640
- 640
rect: true
sync_bn: false
local_rank: -1
cache_images: false
image_weights: false
device: ''
single_cls: false
workers: 2
project: runs/train
name: exp
exist_ok: false
quad: true
world_size: 1
global_rank: -1
save_dir: runs\train\exp
total_batch_size: 8
